// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.sen.proto;

public interface StudentListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sen.proto.StudentList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sen.proto.StudentResponse list = 1;</code>
   */
  java.util.List<com.sen.proto.StudentResponse> 
      getListList();
  /**
   * <code>repeated .com.sen.proto.StudentResponse list = 1;</code>
   */
  com.sen.proto.StudentResponse getList(int index);
  /**
   * <code>repeated .com.sen.proto.StudentResponse list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .com.sen.proto.StudentResponse list = 1;</code>
   */
  java.util.List<? extends com.sen.proto.StudentResponseOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .com.sen.proto.StudentResponse list = 1;</code>
   */
  com.sen.proto.StudentResponseOrBuilder getListOrBuilder(
      int index);
}
