// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.sen.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sen_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sen_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sen_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sen_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sen_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sen_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sen_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sen_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sen_proto_StudentList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sen_proto_StudentList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\rcom.sen.proto\"\035\n\tMyRequ" +
      "est\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010r" +
      "ealname\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001" +
      " \001(\005\">\n\017StudentResponse\022\020\n\010username\030\001 \001(" +
      "\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\";\n\013StudentL" +
      "ist\022,\n\004list\030\001 \001(\0132\036.com.sen.proto.Studen" +
      "tResponse2\205\002\n\016StudentService\022N\n\025GetRealN" +
      "ameByUsername\022\030.com.sen.proto.MyRequest\032" +
      "\031.com.sen.proto.MyResponse\"\000\022R\n\rGetUsers" +
      "ByAge\022\035.com.sen.proto.StudentRequest\032\036.c" +
      "om.sen.proto.StudentResponse\"\0000\001\022O\n\016GetU" +
      "sersByAges\022\035.com.sen.proto.StudentReques" +
      "t\032\032.com.sen.proto.StudentList\"\000(\001B\037\n\rcom" +
      ".sen.protoB\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sen_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sen_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sen_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_sen_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sen_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sen_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_sen_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sen_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sen_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_sen_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_sen_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sen_proto_StudentResponse_descriptor,
        new String[] { "Username", "Age", "City", });
    internal_static_com_sen_proto_StudentList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_sen_proto_StudentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sen_proto_StudentList_descriptor,
        new String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
