// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.sen.proto;

public interface StudentListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sen.proto.StudentList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.sen.proto.StudentResponse list = 1;</code>
   * @return Whether the list field is set.
   */
  boolean hasList();
  /**
   * <code>.com.sen.proto.StudentResponse list = 1;</code>
   * @return The list.
   */
  StudentResponse getList();
  /**
   * <code>.com.sen.proto.StudentResponse list = 1;</code>
   */
  StudentResponseOrBuilder getListOrBuilder();
}
